package it.polimi.ingsw.gc42.model.classes.cards;

public enum Objective {
    FUNGI_COLLECTOR,
    PLANT_COLLECTOR,
    ANIMAL_COLLECTOR,
    INSECT_COLLECTOR,
    POTION_COLLECTOR,
    FEATHER_COLLECTOR,
    SCROLL_COLLECTOR,
    ITEM_COLLECTOR,
    DIAGONAL_RED,
    DIAGONAL_GREEN,
    DIAGONAL_BLUE,
    DIAGONAL_PURPLE,
    L_SHAPED_RED,
    L_SHAPED_GREEN,
    L_SHAPED_BLUE,
    L_SHAPED_PURPLE,
    FOR_EACH_SCROLL,
    FOR_EACH_POTION,
    FOR_EACH_FEATHER,
    FOR_EACH_CORNER
}
